package handlers

import (
	"context"
	"errors"

	"github.com/shopspring/decimal"
	"go.uber.org/zap"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/opus-casino/rg/internal/domain"
	"github.com/opus-casino/rg/internal/service"
)

// RGGrpcHandler exposes RG operations over gRPC.
//
// NOTE: the canonical contract is libs/proto/rg/v1/rg.proto (package rg.v1).
// Go stubs are generated by PROTOBUF_CONTRACTS via `buf generate` into
// libs/proto/gen/go. Until that codegen lands, this handler implements the
// same method surface with plain Go types so the service builds and ships;
// the generated pb.RegisterRGServiceServer wiring replaces the manual
// adapter without touching business logic.
type RGGrpcHandler struct {
	svc *service.RGService
	log *zap.Logger
}

// NewRGGrpcHandler builds the gRPC handler. Panics on nil service.
func NewRGGrpcHandler(svc *service.RGService, log *zap.Logger) *RGGrpcHandler {
	if svc == nil {
		panic("rg: service is required")
	}
	return &RGGrpcHandler{svc: svc, log: log}
}

// CheckPlayAllowed gates one gambling action.
func (h *RGGrpcHandler) CheckPlayAllowed(ctx context.Context, in service.CheckInput) (domain.Decision, error) {
	decision, err := h.svc.CheckPlayAllowed(ctx, in)
	if err != nil {
		return domain.Decision{}, h.mapError(err)
	}
	return decision, nil
}

// SetLimits applies limit changes.
func (h *RGGrpcHandler) SetLimits(ctx context.Context, in service.SetLimitsInput) (*service.SetLimitsResult, error) {
	res, err := h.svc.SetLimits(ctx, in)
	if err != nil {
		return nil, h.mapError(err)
	}
	return res, nil
}

// StartSelfExclusion activates an exclusion.
func (h *RGGrpcHandler) StartSelfExclusion(ctx context.Context, in service.StartSelfExclusionInput) (*domain.Exclusion, error) {
	excl, err := h.svc.StartSelfExclusion(ctx, in)
	if err != nil {
		return nil, h.mapError(err)
	}
	return excl, nil
}

// RecordSpendInput mirrors the service input for transport boundaries.
type RecordSpendInput struct {
	UserID   int64
	Kind     service.SpendKind
	Amount   decimal.Decimal
	Currency string
}

// RecordSpend accumulates settled money movement.
func (h *RGGrpcHandler) RecordSpend(ctx context.Context, in RecordSpendInput) error {
	return h.mapError(h.svc.RecordSpend(ctx, service.RecordSpendInput{
		UserID: in.UserID, Kind: in.Kind, Amount: in.Amount, Currency: in.Currency,
	}))
}

func (h *RGGrpcHandler) mapError(err error) error {
	if err == nil {
		return nil
	}
	var ve *domain.ValidationError
	if errors.As(err, &ve) {
		return status.Error(codes.InvalidArgument, err.Error())
	}
	switch err {
	case domain.ErrSelfExcluded, domain.ErrCoolOffActive:
		return status.Error(codes.PermissionDenied, err.Error())
	case domain.ErrDepositLimit, domain.ErrLossLimit, domain.ErrWagerLimit,
		domain.ErrPermanentExclusion, domain.ErrRevokeTooEarly, domain.ErrRevokeCooling:
		return status.Error(codes.FailedPrecondition, err.Error())
	case domain.ErrExclusionExists, domain.ErrTimeoutExists:
		return status.Error(codes.AlreadyExists, err.Error())
	case domain.ErrExclusionNotFound:
		return status.Error(codes.NotFound, err.Error())
	default:
		return status.Error(codes.Internal, err.Error())
	}
}
