apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification.fullname" . }}-secrets
  labels:
    {{- include "notification.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.env | dig 0 "valueFrom" "secretKeyRef" "" | default "postgres://localhost:5432/notification" | quote }}
  redis-addr: "dragonflydb-data:6379"
  redis-password: {{ .Values.env | dig 1 "valueFrom" "secretKeyRef" "" | default "" | quote }}
  email-api-key: {{ .Values.env | dig 2 "valueFrom" "secretKeyRef" "" | default "" | quote }}
  sms-api-key: {{ .Values.env | dig 3 "valueFrom" "secretKeyRef" "" | default "" | quote }}
  push-firebase-key: {{ .Values.env | dig 4 "valueFrom" "secretKeyRef" "" | default "" | quote }}
