import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Card, Typography, DatePicker, Button, Table, Tag, Space, Select, Row, Col, Statistic } from "antd";
import { ReloadOutlined, DownloadOutlined } from "@ant-design/icons";
import dayjs from "dayjs";
import { paymentsService } from "@/services/payments.service";

const { Title } = Typography;

export default function ComplianceReports() {
  const [dateRange, setDateRange] = useState<[dayjs.Dayjs | null, dayjs.Dayjs | null]>([dayjs().subtract(30, "day"), dayjs()]);
  const [reportType, setReportType] = useState("aml");

  const { data, isLoading, refetch } = useQuery({
    queryKey: ["compliance-report", dateRange[0]?.format("YYYY-MM-DD"), dateRange[1]?.format("YYYY-MM-DD"), reportType],
    queryFn: () => paymentsService.getComplianceReport({
      from: dateRange[0]?.format("YYYY-MM-DD"),
      to: dateRange[1]?.format("YYYY-MM-DD"),
      type: reportType,
    }) as Promise<any>,
  });

  const columns = [
    { title: "Report Date", dataIndex: "report_date" },
    { title: "Type", dataIndex: "type", render: (v: string) => <Tag>{v.toUpperCase()}</Tag> },
    { title: "Flagged Count", dataIndex: "flagged_count" },
    { title: "Resolved", dataIndex: "resolved_count" },
    {
      title: "Risk Level",
      dataIndex: "risk_level",
      render: (v: string) => <Tag color={v === "high" ? "red" : v === "medium" ? "orange" : "green"}>{v.toUpperCase()}</Tag>,
    },
    { title: "Generated By", dataIndex: "generated_by" },
  ];

  return (
    <div>
      <Title level={3}>Compliance Reports</Title>
      <Space style={{ marginBottom: 16 }} wrap>
        <DatePicker.RangePicker value={dateRange as any} onChange={(dates) => setDateRange(dates as any)} />
        <Select value={reportType} onChange={setReportType} style={{ width: 160 }} options={[
          { value: "aml", label: "AML" },
          { value: "rg", label: "Responsible Gaming" },
          { value: "kyc", label: "KYC Verification" },
          { value: "audit", label: "Audit Trail" },
        ]} />
        <Button icon={<ReloadOutlined />} onClick={() => refetch()} loading={isLoading}>Generate</Button>
        <Button icon={<DownloadOutlined />} disabled={!data}>Export PDF</Button>
      </Space>
      <Row gutter={16} style={{ marginBottom: 16 }}>
        <Col span={6}><Card><Statistic title="Flagged" value={data?.flagged || 0} /></Card></Col>
        <Col span={6}><Card><Statistic title="Resolved" value={data?.resolved || 0} /></Card></Col>
        <Col span={6}><Card><Statistic title="Pending" value={data?.pending || 0} valueStyle={{ color: "#faad14" }} /></Card></Col>
        <Col span={6}><Card><Statistic title="High Risk" value={data?.high_risk || 0} valueStyle={{ color: "#cf1322" }} /></Card></Col>
      </Row>
      <Card>
        <Table rowKey="id" dataSource={data?.rows || []} columns={columns} loading={isLoading} pagination={{ pageSize: 20 }} />
      </Card>
    </div>
  );
}
