apiVersion: v1
kind: Secret
metadata:
  name: {{ include "casino.fullname" . }}-secrets
  labels:
    {{- include "casino.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.env | dig 0 "valueFrom" "secretKeyRef" "" | default "postgres://localhost:5432/casino" | quote }}
  redis-addr: "dragonflydb-data:6379"
  redis-password: {{ .Values.env | dig 1 "valueFrom" "secretKeyRef" "" | default "" | quote }}
