apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fraud-ml.fullname" . }}-secrets
  labels:
    {{- include "fraud-ml.labels" . | nindent 4 }}
type: Opaque
stringData:
  clickhouse-user: {{ .Values.ml.clickhouse.user | default "fraud_ml" | quote }}
  clickhouse-password: {{ .Values.ml.clickhouse.password | default "" | quote }}
